# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 647)
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(390, 40, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(40, 320, 81, 16))
        self.label_3.setObjectName("label_3")
        self.txt_info = QtWidgets.QTextEdit(MainWindow)
        self.txt_info.setGeometry(QtCore.QRect(160, 120, 701, 141))
        self.txt_info.setObjectName("txt_info")
        self.txt_sign = QtWidgets.QTextEdit(MainWindow)
        self.txt_sign.setGeometry(QtCore.QRect(160, 320, 701, 141))
        self.txt_sign.setObjectName("txt_sign")
        self.btn_sign = QtWidgets.QPushButton(MainWindow)
        self.btn_sign.setGeometry(QtCore.QRect(160, 540, 141, 41))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(MainWindow)
        self.btn_verify.setGeometry(QtCore.QRect(710, 540, 141, 41))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_gen_keys = QtWidgets.QPushButton(MainWindow)
        self.btn_gen_keys.setGeometry(QtCore.QRect(710, 40, 141, 41))
        self.btn_gen_keys.setObjectName("btn_gen_keys")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.label.setText(_translate("MainWindow", "ECC Cipher Demo"))
        self.label_2.setText(_translate("MainWindow", "Infomation"))
        self.label_3.setText(_translate("MainWindow", "Signature"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
